name: copy public to prod

on:
  push:
    branches:
      - public
  workflow_dispatch:

jobs:
  trigger-mirror:
    if: github.repository == 'ed-ev/lbol-logs-dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: public
      - run: |
          git clone --bare https://ed-ev:${{ secrets.PAT }}@github.com/ed-ev/lbol-logs-dev.git --single-branch --branch public lbol-logs
          cd lbol-logs
          git remote add public https://github.com/ed-ev/lbol-logs.git
          git push public public
